### ISSUE TITLE
Sibling query half: :include fails in 2.0.2

### ISSUE THREAD

**Issue by adrianscott83** [masciugo/genealogy#10]
The query for siblings `@member.siblings(half: :include)` fails due to an invalid query:

`ERROR:  operator does not exist: integer == integer`

Seems that Postgres (and probably other SQL languages) do not support the double equals operator.  Found at line 104 of query_methods.rb.

**Comment by masciugo** [comment]
ok connecting to mysql makes some tests fail because of that. Thanks, I'll look into it. thankyou

**Comment by adrianscott83** [comment]
Thanks!  Loving the work you've done, by the way.

**Comment by masciugo** [comment]
Should be ok in 2.1.1 (I made an extra version bump by mistake). Travis tests added for mysql and postgres.
