### ISSUE TITLE
Rails 5.2 class instead of class_name depreciation warning 

### ISSUE THREAD

**Issue by gdemonie** [masciugo/genealogy#17]
Hi, thanks for the great gem.
Having upgraded to rails 5.1, I'm getting the following depreciation warning:
Passing a class to the `class_name` is deprecated and will raise an ArgumentError in Rails 5.2. It eagerloads more classes than necessary and potentially creates circular dependencies. Please pass the class name as a string: `belongs_to :father
Should be an easy fix by passing self.class_name instead of self in the belongs_to and has_many relationships?
Thanks!

**Comment by masciugo** [comment]
to be honest I have not faced yet the upgrade to rails 5. So the fact you are getting only this kind of problems is a good news. I think that your solution is the right one, even in general: class_name option wants a name not a class. 
Please go ahead with a pull request if you can as I'll be back to this project not before than a month

**Comment by masciugo** [comment]
released version 2.2 (rails 5.2 compliant)
